apiVersion: monitoring.rhobs/v1
kind: ServiceMonitor
metadata:
  name: otel-collector-spanmetrics
  namespace: observability
  annotations:
    argocd.argoproj.io/sync-wave: "3"
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
  labels:
    observability: platform
    app.kubernetes.io/name: opentelemetry
    app.kubernetes.io/component: collector
    app.kubernetes.io/part-of: observability
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: otel-collector-collector
      operator.opentelemetry.io/collector-service-type: base
  endpoints:
    - port: spanmetrics
      interval: 30s
      scrapeTimeout: 10s
