apiVersion: v1
kind: ConfigMap
metadata:
  name: cluster-monitoring-config
  namespace: openshift-monitoring
  annotations:
    argocd.argoproj.io/sync-wave: "0"
data:
  config.yaml: |
    enableUserWorkload: true
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: otel-collector-spanmetrics
  namespace: observability
  annotations:
    argocd.argoproj.io/sync-wave: "3"
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: otel-collector-collector
      operator.opentelemetry.io/collector-service-type: base
  endpoints:
    - port: spanmetrics
      interval: 30s
      scrapeTimeout: 10s
